.TH "test Directory Reference" 3 "Mon Nov 11 2019" "Version 1.0" "beginner_tutorials" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.RI "\fIMain for testing\&. \fP"
.ti -1c
.RI "file \fBtestTalker\&.cpp\fP"
.br
.RI "\fITests for \fBtalker\&.cpp\fP\&. \fP"
.in -1c
