.TH "test/main.cpp" 3 "Mon Nov 11 2019" "Version 1.0" "beginner_tutorials" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/main.cpp \- Main for testing\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <gtest/gtest\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "\fIMain for testing\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Main for testing\&. 


.PP
\fBCopyright:\fP
.RS 4
MIT License, © 2019 Raj Shinde
.RE
.PP
\fBAuthor:\fP
.RS 4
Raj Shinde 
.RE
.PP
\fBDate:\fP
.RS 4
11/10/2019 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
.SH "DESCRIPTION"
.PP
All the test are run 
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Main for testing\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargc\fP no of argumnets 
.br
\fIargv\fP char pointer consisting arguments 
.RE
.PP
\fBReturns:\fP
.RS 4
RUN_ALL_TESTS() 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for beginner_tutorials from the source code\&.
