.TH "test/testTalker.cpp" 3 "Mon Nov 11 2019" "Version 1.0" "beginner_tutorials" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/testTalker.cpp \- Tests for \fBtalker\&.cpp\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <tf/transform_listener\&.h>\fP
.br
\fC#include <ros/service_client\&.h>\fP
.br
\fC#include <std_msgs/String\&.h>\fP
.br
\fC#include 'beginner_tutorials/serviceString\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (Talker, testService)"
.br
.RI "\fIA unit test to check that the talker string service works correctly\&. \fP"
.ti -1c
.RI "\fBTEST\fP (Talker, testTf)"
.br
.RI "\fIA unit test to check the Broadcasted frames offset\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Tests for \fBtalker\&.cpp\fP\&. 


.PP
\fBCopyright:\fP
.RS 4
MIT License, © 2019 Raj Shinde
.RE
.PP
\fBAuthor:\fP
.RS 4
Raj Shinde 
.RE
.PP
\fBDate:\fP
.RS 4
11/10/2019 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
.SH "DESCRIPTION"
.PP
Test are written for talker node 
.SH "Author"
.PP 
Generated automatically by Doxygen for beginner_tutorials from the source code\&.
