.TH "X" 3 "Mon Nov 11 2019" "Version 1.0" "beginner_tutorials" \" -*- nroff -*-
.ad l
.nh
.SH NAME
X \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::string\fP \fBtemp\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for beginner_tutorials from the source code\&.
